#configmap configuration
configuration:
  loglevel: ERROR

#container configuration
container:
  containerPort: 8080
  protocol: TCP
  resources:
    requests:
      memory: 0.2Gi
      cpu: 0.1
    limits:
      memory: 0.5Gi
      cpu: 0.3

#deployment configuration
deploy:
  env: prod
  replicas: 2
  aws_test_connection_max_retries: 30

#Service configuration
service:
  ports:
    servicePort: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP

#Sidecar event configuration
events:
  consumerPollMillis: 1000
  consumerMaxPollRecords: 100
  kafkaSendTimeWaitLimit: 5000
  httpThreads: 100
  requestMemory: "0.4Gi"
  requestCpu: "0.1"
  limitMemory: "1Gi"
  limitCpu: "0.5"
